# Generated by Django 3.1.1 on 2020-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201104_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.JSONField(default={}),
        ),
    ]
