# Generated by Django 3.1.1 on 2020-11-15 17:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201115_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('41e74865-863a-466e-a880-e7cb97915abf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
