# Generated by Django 3.1.1 on 2020-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201104_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
