# Generated by Django 3.1.1 on 2021-01-21 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20201115_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 21, 18, 48, 51, 820489, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('37a5fc64-ba4c-47fa-b87b-23841bdea154'), editable=False, primary_key=True, serialize=False),
        ),
    ]
