# Generated by Django 3.1.1 on 2020-11-04 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20201104_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63a0c451-329c-4c18-84bb-409507ea6e67'), editable=False, primary_key=True, serialize=False),
        ),
    ]
