# Generated by Django 3.1.1 on 2020-11-04 09:22

import boards.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20201104_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.JSONField(default=boards.models.defult_dict),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f23c2839-a963-49dd-aebf-8f1bd2fb0702'), editable=False, primary_key=True, serialize=False),
        ),
    ]
