# Generated by Django 3.1.1 on 2020-11-04 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20201104_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52510310-f953-4e61-bf82-bec4c609dcd8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
