# Generated by Django 3.1.1 on 2020-11-04 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20201104_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e22089e-ab5d-4dc3-9a7c-9d7454df6813'), editable=False, primary_key=True, serialize=False),
        ),
    ]
